name: Go Test and Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-bench:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./... -v -cover

      - name: Run Benchmarks
        run: go test ./... -bench=. -benchmem